### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by srolandmarshall** [learn-co-curriculum/crud-lab#11]
If you make the ReviewInput a `<textarea>` instead of `<input>` the test to recognize it as a text input field passes but the Change State/Store tests fail.

Example:

`<textarea
              type="textarea"
              placeholder="Write your review..."
              value={this.state.text}
              onChange={this.handleChange} />
            <input type="submit" />`

Fails the following tests: 
``` 
1) ReviewInput Component
       has changes the state on a keydown:

      AssertionError: expected '' to equal 'Hello'
      + expected - actual

      +Hello

      at Context.<anonymous> (test/reviews-test.js:43:38)

  2) ReviewInput Component
       adds a review to the store when the form is submitted:
     AssertionError: expected '<div><li></li><button> X </button></div>' to include 'Better Ingredients'
      at Context.<anonymous> (test/reviews-test.js:60:44)
```

But 
` <input
              type="text"
              placeholder="Write your review..."
              value={this.state.text}
              onChange={this.handleChange} />
            <input type="submit" />` passes the above.

The above tests include a test that checks for text input field:
```
    ✓ displays the ReviewInput component as a child of each Restaurant Component
    ✓ has a text input field /* Right here */
    ✓ has an initial state with text key set to empty string
```

But `<textarea>` doesn't fail that criteria. Leads to a maddening bug hunt that doesn't exist.

**Comment by maxwellbenton** [comment]
Hi @srolandmarshall,

Thank you for spotting this and providing thorough feedback. We've identified an issue with the tests in this lab (they were looking for an `input`, but since there _is_ a submit button `input`, they were passing). We've updated the tests to check for _two_ `input` elements now and included a message in the Readme noting to use only `input` elements, which should resolve this and prevent future students from encountering this.

We apologize for the frustration this bug caused, but we appreciate you taking the time to help improve our materials!

Thank you!
